sudo: required
services:
  - docker

before_install:
  - docker build -t rdangal1/reactboilerplate -f Dockerfile.dev .

script:
  - echo 'test ran'

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-145586335677"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"